language: python

python:
- '3.4'
- '3.5'

install:
- pip install -r test_requirements.txt

script:
- python setup.py test

# Don't compile "experimental" branches starting with x-, y-, or z-.
branches:
  except:
    - /^x-.*$/
    - /^y-.*$/
    - /^z-.*$/
